// AUTO-GENERATED by scripts/generate-gallery-data.mjs — do not edit by hand.

export interface GalleryCategoryData {
  slug: string;
  label: string;
  images: string[];
}

export const galleryCategories: GalleryCategoryData[] = [
  {
    "slug": "internationalrelationships",
    "label": "International Relationships",
    "images": [
      "/gallery/InternationalRelationships/1000012940%20(2).jpg",
      "/gallery/InternationalRelationships/1742466626483.jpg",
      "/gallery/InternationalRelationships/645415829_1473917357666269_3248638999310121300_n.jpg",
      "/gallery/InternationalRelationships/IMG-20260511-WA0004.jpg",
      "/gallery/InternationalRelationships/IMG-20260511-WA0038.jpg",
      "/gallery/InternationalRelationships/IMG-20260511-WA0052.jpg",
      "/gallery/InternationalRelationships/IMG-20260512-WA0012.jpg"
    ]
  },
  {
    "slug": "project-ashaa",
    "label": "Project ASHAA",
    "images": [
      "/gallery/Project%20ASHAA/342980508_187654830818724_2453866954384914874_n.jpg",
      "/gallery/Project%20ASHAA/491023587_523214477314068_4343446260111957405_n.jpg",
      "/gallery/Project%20ASHAA/Bamboo%20Hair%20Pin%20(1).jpg",
      "/gallery/Project%20ASHAA/IMG-20220910-WA0007.jpg",
      "/gallery/Project%20ASHAA/IMG-20220910-WA0009.jpg",
      "/gallery/Project%20ASHAA/Training%20women%20Mymensingh.jpg"
    ]
  },
  {
    "slug": "recognition-for-work",
    "label": "Recognition for Work",
    "images": [
      "/gallery/Recognition%20for%20Work/1750581940114.jpg",
      "/gallery/Recognition%20for%20Work/1764168731470.jpg",
      "/gallery/Recognition%20for%20Work/647169989_1459673485827227_7110581376347399087_n.jpg",
      "/gallery/Recognition%20for%20Work/81266a77-50c1-40d3-841c-6a8166e9ebc3%20(1).jpg",
      "/gallery/Recognition%20for%20Work/IMG-20260511-WA0035.jpg",
      "/gallery/Recognition%20for%20Work/IMG-20260511-WA0036.jpg",
      "/gallery/Recognition%20for%20Work/IMG-20260512-WA0006.jpg",
      "/gallery/Recognition%20for%20Work/With%20Dr%20Yunus.jpg"
    ]
  },
  {
    "slug": "research-paper",
    "label": "Research Paper",
    "images": [
      "/gallery/Research%20Paper/IMG_20260512_000307.jpg",
      "/gallery/Research%20Paper/IMG_20260512_000403.jpg",
      "/gallery/Research%20Paper/IMG_20260512_000525.jpg"
    ]
  },
  {
    "slug": "some-partnerships",
    "label": "Some Partnerships",
    "images": [
      "/gallery/Some%20Partnerships/1000012937.jpg",
      "/gallery/Some%20Partnerships/1756630250464%20(1).jpg",
      "/gallery/Some%20Partnerships/470546790_446816838472403_3769150673681619267_n.jpg",
      "/gallery/Some%20Partnerships/IMG_1161.JPG.JPG",
      "/gallery/Some%20Partnerships/IMG-20260511-WA0001.jpg",
      "/gallery/Some%20Partnerships/IMG-20260511-WA0002.jpg",
      "/gallery/Some%20Partnerships/IMG-20260511-WA0049.jpg",
      "/gallery/Some%20Partnerships/IMG-20260511-WA0061.jpg",
      "/gallery/Some%20Partnerships/NL1A5447-1.JPG",
      "/gallery/Some%20Partnerships/WhatsApp%20Image%202026-05-12%20at%2012.28.46%20AM%20(1).jpeg"
    ]
  },
  {
    "slug": "unesco-green-generation-campaign",
    "label": "UNESCO Green Generation Campaign",
    "images": [
      "/gallery/UNESCO%20Green%20Generation%20Campaign%20/621666613_122108710221203514_5418739182527504935_n.jpg",
      "/gallery/UNESCO%20Green%20Generation%20Campaign%20/621845463_122108711277203514_6177943819171270056_n.jpg",
      "/gallery/UNESCO%20Green%20Generation%20Campaign%20/623370543_122109846165203514_1901192167932488758_n.jpg",
      "/gallery/UNESCO%20Green%20Generation%20Campaign%20/623690159_122109162765203514_3719195079804343042_n.jpg",
      "/gallery/UNESCO%20Green%20Generation%20Campaign%20/628258952_122110513437203514_3660112883627273544_n.jpg",
      "/gallery/UNESCO%20Green%20Generation%20Campaign%20/629222168_122110885599203514_7076988436825389741_n.jpg",
      "/gallery/UNESCO%20Green%20Generation%20Campaign%20/629226995_122110885545203514_5817612138263401283_n.jpg",
      "/gallery/UNESCO%20Green%20Generation%20Campaign%20/629349392_122111300709203514_6707121896704298637_n.jpg",
      "/gallery/UNESCO%20Green%20Generation%20Campaign%20/635118658_122112591021203514_5949234924038489382_n.jpg",
      "/gallery/UNESCO%20Green%20Generation%20Campaign%20/IMG_0225.jpg",
      "/gallery/UNESCO%20Green%20Generation%20Campaign%20/IMG_2712.jpg",
      "/gallery/UNESCO%20Green%20Generation%20Campaign%20/IMG20260115154539.jpg",
      "/gallery/UNESCO%20Green%20Generation%20Campaign%20/IMG20260115155111.jpg"
    ]
  }
];
